# Generated by Django 6.1.1 on 2026-09-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrainementHMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entrainement', models.CharField(choices=[('initial', 'Entraînement initial (train)'), ('walk_forward', 'Ré-entraînement walk-forward (test)')], max_length=15)),
                ('date_debut_fenetre', models.DateField()),
                ('date_fin_fenetre', models.DateField()),
                ('nb_observations', models.IntegerField()),
                ('log_vraisemblance', models.FloatField()),
                ('date_application_debut', models.DateField()),
                ('date_application_fin', models.DateField()),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entraînement HMM',
                'verbose_name_plural': 'Entraînements HMM',
                'ordering': ['date_debut_fenetre'],
            },
        ),
    ]
