"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tlltk6f2e2x9%qjpm&dh0+l5*n)zq0^tae45q#q(jn%8ckv^=&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    # Apps du projet HMM CAC40
    'apps.market_data',
    'apps.regimes',
    'apps.portfolio',
    'apps.dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']
NPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd'


# Paramètres spécifiques au projet HMM CAC40
# Dossier de données (fichiers DuckDB, exports) et paramètres de marché
DATA_DIR = BASE_DIR / 'data'
DUCKDB_PATH = DATA_DIR / 'marche.duckdb'
UNIVERS_CAC40_CSV = BASE_DIR / 'config' / 'univers_cac40.csv'

# Fenêtre historique figée (reproductibilité, cf. docs/02_donnees_marche.md)
DATE_DEBUT_HISTORIQUE = '2016-09-10'
DATE_FIN_HISTORIQUE = '2026-09-10'
TICKER_BENCHMARK = '^FCHI'

# Séries FRED pour le spread de taux France - Allemagne (cf. docs/02_donnees_marche.md)
FRED_SERIE_TAUX_FRANCE = 'IRLTLT01FRM156N'
FRED_SERIE_TAUX_ALLEMAGNE = 'IRLTLT01DEM156N'
# Taux sans risque (taux interbancaire 3 mois France), utilisé pour Sharpe/Sortino
FRED_SERIE_TAUX_SANS_RISQUE = 'IR3TIB01FRM156N'

# Paramètres du modèle HMM de détection de régimes (cf. docs/03_modele_hmm.md)
HMM_NB_ETATS = 3
HMM_FENETRE_VOLATILITE_JOURS = 20
HMM_FREQUENCE_REENTRAINEMENT_JOURS = 63
SPLIT_TRAIN_RATIO = 0.7
# Prior de transition "collant" (favorise la persistance d'état, réduit le whipsaw)
HMM_TRANSMAT_PRIOR_DIAGONAL = 20.0
# Filtre de persistance causal : un changement de régime n'est confirmé que s'il
# persiste au moins ce nombre de jours de bourse consécutifs (cf. docs/03_modele_hmm.md)
HMM_PERSISTANCE_MIN_JOURS = 5

# Paramètres du bêta et de l'allocation (cf. docs/04_beta_allocation.md)
BETA_FENETRE_JOURS = 252
BETA_SEUIL_DEFENSIF = 0.8
BETA_SEUIL_NEUTRE_BAS = 0.9
BETA_SEUIL_NEUTRE_HAUT = 1.1
BETA_SEUIL_OFFENSIF = 1.2
PANIER_TAILLE_CIBLE = 10
PANIER_TAILLE_BUFFER = 15
# Décidé après comparaison empirique (cf. python manage.py comparer_ajustement_beta) :
# Blume réduit le turnover de ~13% (1681 vs 1940 sur 471 semaines) pour une taille de
# panier moyenne quasi identique (9.11 vs 9.67).
UTILISER_BLUME = True

# Phase 4 (bis) — correctifs de sous-performance (cf. docs/04 et 05) :
# rééquilibrage mensuel (régimes plus significatifs, moins de bruit/coûts) +
# allocation probabiliste (pondération par les probabilités de régime, pas de bascule
# 100% dure) + filtre qualité/momentum en complément du bêta pur.
FREQUENCE_REEQUILIBRAGE = 'mensuel'
MOMENTUM_FENETRE_JOURS = 63
POIDS_SCORE_BETA = 0.6
POIDS_SCORE_MOMENTUM = 0.4
# Atténuation du biais défensif en régime baissier : les creux de marché sont souvent
# suivis d'un rebond à court terme (cf. diagnostic Phase 4, docs/05_backtest_metriques.md).
# Seule cette fraction de la probabilité "baissier" reste allouée au panier défensif ;
# le reste est réalloué au panier neutre pour capter une partie du rebond.
ATTENUATION_BAISSIER = 1.0

# Paramètres du backtest (cf. docs/05_backtest_metriques.md)
CAPITAL_INITIAL = 1_000_000
COUT_TRANSACTION_POURCENT = 0.001
VAR_NIVEAU_CONFIANCE = 0.95


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
