# Generated by Django 6.1.1 on 2026-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDonneesMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('date_debut_historique', models.DateField()),
                ('date_fin_historique', models.DateField()),
                ('date_dernier_import', models.DateTimeField(auto_now=True)),
                ('nb_lignes_importees', models.IntegerField(default=0)),
                ('taux_valeurs_manquantes', models.FloatField(default=0.0)),
                ('statut', models.CharField(choices=[('ok', 'Import réussi'), ('echec', 'Échec'), ('exclu', 'Exclu (trop de données manquantes)')], default='echec', max_length=10)),
                ('message_erreur', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Import de données marché',
                'verbose_name_plural': 'Imports de données marché',
                'ordering': ['ticker'],
            },
        ),
    ]
