# Generated by Django 6.1.1 on 2026-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('utilise_blume', models.BooleanField()),
                ('nb_semaines', models.IntegerField()),
                ('turnover_total', models.IntegerField(help_text="Nombre total d'entrées + sorties de panier sur la période")),
                ('taille_panier_moyenne', models.FloatField()),
            ],
            options={
                'verbose_name': 'Exécution allocation',
                'verbose_name_plural': 'Exécutions allocation',
                'ordering': ['-date_execution'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionCalculBeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('fenetre_jours', models.IntegerField()),
                ('nb_tickers', models.IntegerField()),
                ('nb_dates_hebdomadaires', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Exécution calcul bêta',
                'verbose_name_plural': 'Exécutions calcul bêta',
                'ordering': ['-date_execution'],
            },
        ),
    ]
