# Generated by Django 6.1.1 on 2026-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionBacktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('date_debut_test', models.DateField()),
                ('date_fin_test', models.DateField()),
                ('capital_initial', models.FloatField()),
                ('capital_final_portefeuille', models.FloatField()),
                ('rendement_annualise_portefeuille', models.FloatField()),
                ('volatilite_portefeuille', models.FloatField()),
                ('sharpe_portefeuille', models.FloatField()),
                ('sortino_portefeuille', models.FloatField()),
                ('calmar_portefeuille', models.FloatField()),
                ('max_drawdown_portefeuille', models.FloatField()),
                ('var_95_portefeuille', models.FloatField()),
                ('capital_final_benchmark', models.FloatField()),
                ('rendement_annualise_benchmark', models.FloatField()),
                ('volatilite_benchmark', models.FloatField()),
                ('sharpe_benchmark', models.FloatField()),
                ('max_drawdown_benchmark', models.FloatField()),
                ('alpha_annualise', models.FloatField()),
                ('beta_portefeuille', models.FloatField()),
                ('taux_sans_risque_moyen', models.FloatField()),
                ('cout_transactions_total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Exécution backtest',
                'verbose_name_plural': 'Exécutions backtest',
                'ordering': ['-date_execution'],
            },
        ),
    ]
